# Generated by Django 4.2.10 on 2024-03-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='firstName of User'),
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='shiraishi Masayuki', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='lastName of User'),
        ),
        migrations.AddField(
            model_name='user',
            name='mail_verify_statu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=255, verbose_name='phone Number of User'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/user_images'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('User', 'User'), ('Developer', 'Developer'), ('Investor', 'Investor')], default='User', max_length=50),
        ),
    ]
