# Generated by Django 4.2.10 on 2024-07-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_phonenumber_user_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='Authentication Code'),
        ),
    ]
