# Generated by Django 4.2.10 on 2024-07-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='authority_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
